"""attempt kind

Revision ID: 2b9cbe200329
Revises: 1c72959e624d
Create Date: 2026-09-17 15:16:44.162221

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b9cbe200329"
down_revision: str | Sequence[str] | None = "1c72959e624d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercise_attempts", sa.Column("kind", sa.String(length=10), server_default="lesson", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercise_attempts", "kind")
    # ### end Alembic commands ###
